package faang.school.postservice.protobuf.generate;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: feed_event.proto
// Protobuf Java Version: 4.28.2

public final class FeedEventProto {
  private FeedEventProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      FeedEventProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FeedEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FeedEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 postId = 1;</code>
     * @return The postId.
     */
    long getPostId();

    /**
     * <code>repeated int64 followerIds = 2;</code>
     * @return A list containing the followerIds.
     */
    java.util.List<java.lang.Long> getFollowerIdsList();
    /**
     * <code>repeated int64 followerIds = 2;</code>
     * @return The count of followerIds.
     */
    int getFollowerIdsCount();
    /**
     * <code>repeated int64 followerIds = 2;</code>
     * @param index The index of the element to return.
     * @return The followerIds at the given index.
     */
    long getFollowerIds(int index);
  }
  /**
   * Protobuf type {@code FeedEvent}
   */
  public static final class FeedEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:FeedEvent)
      FeedEventOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        FeedEvent.class.getName());
    }
    // Use FeedEvent.newBuilder() to construct.
    private FeedEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private FeedEvent() {
      followerIds_ = emptyLongList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FeedEventProto.internal_static_FeedEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FeedEventProto.internal_static_FeedEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FeedEventProto.FeedEvent.class, FeedEventProto.FeedEvent.Builder.class);
    }

    public static final int POSTID_FIELD_NUMBER = 1;
    private long postId_ = 0L;
    /**
     * <code>int64 postId = 1;</code>
     * @return The postId.
     */
    @java.lang.Override
    public long getPostId() {
      return postId_;
    }

    public static final int FOLLOWERIDS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.LongList followerIds_ =
        emptyLongList();
    /**
     * <code>repeated int64 followerIds = 2;</code>
     * @return A list containing the followerIds.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getFollowerIdsList() {
      return followerIds_;
    }
    /**
     * <code>repeated int64 followerIds = 2;</code>
     * @return The count of followerIds.
     */
    public int getFollowerIdsCount() {
      return followerIds_.size();
    }
    /**
     * <code>repeated int64 followerIds = 2;</code>
     * @param index The index of the element to return.
     * @return The followerIds at the given index.
     */
    public long getFollowerIds(int index) {
      return followerIds_.getLong(index);
    }
    private int followerIdsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (postId_ != 0L) {
        output.writeInt64(1, postId_);
      }
      if (getFollowerIdsList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(followerIdsMemoizedSerializedSize);
      }
      for (int i = 0; i < followerIds_.size(); i++) {
        output.writeInt64NoTag(followerIds_.getLong(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (postId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, postId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < followerIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(followerIds_.getLong(i));
        }
        size += dataSize;
        if (!getFollowerIdsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        followerIdsMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FeedEventProto.FeedEvent)) {
        return super.equals(obj);
      }
      FeedEventProto.FeedEvent other = (FeedEventProto.FeedEvent) obj;

      if (getPostId()
          != other.getPostId()) return false;
      if (!getFollowerIdsList()
          .equals(other.getFollowerIdsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POSTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPostId());
      if (getFollowerIdsCount() > 0) {
        hash = (37 * hash) + FOLLOWERIDS_FIELD_NUMBER;
        hash = (53 * hash) + getFollowerIdsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FeedEventProto.FeedEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FeedEventProto.FeedEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FeedEventProto.FeedEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FeedEventProto.FeedEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FeedEventProto.FeedEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FeedEventProto.FeedEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FeedEventProto.FeedEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static FeedEventProto.FeedEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static FeedEventProto.FeedEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static FeedEventProto.FeedEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FeedEventProto.FeedEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static FeedEventProto.FeedEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FeedEventProto.FeedEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FeedEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FeedEvent)
        FeedEventProto.FeedEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FeedEventProto.internal_static_FeedEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FeedEventProto.internal_static_FeedEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FeedEventProto.FeedEvent.class, FeedEventProto.FeedEvent.Builder.class);
      }

      // Construct using faang.school.postservice.protobuf.generate.FeedEventProto.FeedEvent.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        postId_ = 0L;
        followerIds_ = emptyLongList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FeedEventProto.internal_static_FeedEvent_descriptor;
      }

      @java.lang.Override
      public FeedEventProto.FeedEvent getDefaultInstanceForType() {
        return FeedEventProto.FeedEvent.getDefaultInstance();
      }

      @java.lang.Override
      public FeedEventProto.FeedEvent build() {
        FeedEventProto.FeedEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public FeedEventProto.FeedEvent buildPartial() {
        FeedEventProto.FeedEvent result = new FeedEventProto.FeedEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(FeedEventProto.FeedEvent result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.postId_ = postId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          followerIds_.makeImmutable();
          result.followerIds_ = followerIds_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FeedEventProto.FeedEvent) {
          return mergeFrom((FeedEventProto.FeedEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FeedEventProto.FeedEvent other) {
        if (other == FeedEventProto.FeedEvent.getDefaultInstance()) return this;
        if (other.getPostId() != 0L) {
          setPostId(other.getPostId());
        }
        if (!other.followerIds_.isEmpty()) {
          if (followerIds_.isEmpty()) {
            followerIds_ = other.followerIds_;
            followerIds_.makeImmutable();
            bitField0_ |= 0x00000002;
          } else {
            ensureFollowerIdsIsMutable();
            followerIds_.addAll(other.followerIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                postId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                long v = input.readInt64();
                ensureFollowerIdsIsMutable();
                followerIds_.addLong(v);
                break;
              } // case 16
              case 18: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureFollowerIdsIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  followerIds_.addLong(input.readInt64());
                }
                input.popLimit(limit);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long postId_ ;
      /**
       * <code>int64 postId = 1;</code>
       * @return The postId.
       */
      @java.lang.Override
      public long getPostId() {
        return postId_;
      }
      /**
       * <code>int64 postId = 1;</code>
       * @param value The postId to set.
       * @return This builder for chaining.
       */
      public Builder setPostId(long value) {

        postId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 postId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPostId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        postId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.LongList followerIds_ = emptyLongList();
      private void ensureFollowerIdsIsMutable() {
        if (!followerIds_.isModifiable()) {
          followerIds_ = makeMutableCopy(followerIds_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <code>repeated int64 followerIds = 2;</code>
       * @return A list containing the followerIds.
       */
      public java.util.List<java.lang.Long>
          getFollowerIdsList() {
        followerIds_.makeImmutable();
        return followerIds_;
      }
      /**
       * <code>repeated int64 followerIds = 2;</code>
       * @return The count of followerIds.
       */
      public int getFollowerIdsCount() {
        return followerIds_.size();
      }
      /**
       * <code>repeated int64 followerIds = 2;</code>
       * @param index The index of the element to return.
       * @return The followerIds at the given index.
       */
      public long getFollowerIds(int index) {
        return followerIds_.getLong(index);
      }
      /**
       * <code>repeated int64 followerIds = 2;</code>
       * @param index The index to set the value at.
       * @param value The followerIds to set.
       * @return This builder for chaining.
       */
      public Builder setFollowerIds(
          int index, long value) {

        ensureFollowerIdsIsMutable();
        followerIds_.setLong(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 followerIds = 2;</code>
       * @param value The followerIds to add.
       * @return This builder for chaining.
       */
      public Builder addFollowerIds(long value) {

        ensureFollowerIdsIsMutable();
        followerIds_.addLong(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 followerIds = 2;</code>
       * @param values The followerIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllFollowerIds(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureFollowerIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, followerIds_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 followerIds = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFollowerIds() {
        followerIds_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:FeedEvent)
    }

    // @@protoc_insertion_point(class_scope:FeedEvent)
    private static final FeedEventProto.FeedEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FeedEventProto.FeedEvent();
    }

    public static FeedEventProto.FeedEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FeedEvent>
        PARSER = new com.google.protobuf.AbstractParser<FeedEvent>() {
      @java.lang.Override
      public FeedEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FeedEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FeedEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public FeedEventProto.FeedEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FeedEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FeedEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020feed_event.proto\"0\n\tFeedEvent\022\016\n\006postI" +
      "d\030\001 \001(\003\022\023\n\013followerIds\030\002 \003(\003B\020B\016FeedEven" +
      "tProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FeedEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FeedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FeedEvent_descriptor,
        new java.lang.String[] { "PostId", "FollowerIds", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
