package faang.school.postservice.protobuf.generate;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: post_published_event.proto
// Protobuf Java Version: 4.28.3

public final class PostPublishedEventProto {
  private PostPublishedEventProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      PostPublishedEventProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PostPublishedEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PostPublishedEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 postId = 1;</code>
     * @return The postId.
     */
    long getPostId();

    /**
     * <code>int64 authorId = 2;</code>
     * @return The authorId.
     */
    long getAuthorId();

    /**
     * <code>repeated int64 subscribersIds = 3;</code>
     * @return A list containing the subscribersIds.
     */
    java.util.List<java.lang.Long> getSubscribersIdsList();
    /**
     * <code>repeated int64 subscribersIds = 3;</code>
     * @return The count of subscribersIds.
     */
    int getSubscribersIdsCount();
    /**
     * <code>repeated int64 subscribersIds = 3;</code>
     * @param index The index of the element to return.
     * @return The subscribersIds at the given index.
     */
    long getSubscribersIds(int index);
  }
  /**
   * Protobuf type {@code PostPublishedEvent}
   */
  public static final class PostPublishedEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PostPublishedEvent)
      PostPublishedEventOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        PostPublishedEvent.class.getName());
    }
    // Use PostPublishedEvent.newBuilder() to construct.
    private PostPublishedEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PostPublishedEvent() {
      subscribersIds_ = emptyLongList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PostPublishedEventProto.internal_static_PostPublishedEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PostPublishedEventProto.internal_static_PostPublishedEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PostPublishedEventProto.PostPublishedEvent.class, PostPublishedEventProto.PostPublishedEvent.Builder.class);
    }

    public static final int POSTID_FIELD_NUMBER = 1;
    private long postId_ = 0L;
    /**
     * <code>int64 postId = 1;</code>
     * @return The postId.
     */
    @java.lang.Override
    public long getPostId() {
      return postId_;
    }

    public static final int AUTHORID_FIELD_NUMBER = 2;
    private long authorId_ = 0L;
    /**
     * <code>int64 authorId = 2;</code>
     * @return The authorId.
     */
    @java.lang.Override
    public long getAuthorId() {
      return authorId_;
    }

    public static final int SUBSCRIBERSIDS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.LongList subscribersIds_ =
        emptyLongList();
    /**
     * <code>repeated int64 subscribersIds = 3;</code>
     * @return A list containing the subscribersIds.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getSubscribersIdsList() {
      return subscribersIds_;
    }
    /**
     * <code>repeated int64 subscribersIds = 3;</code>
     * @return The count of subscribersIds.
     */
    public int getSubscribersIdsCount() {
      return subscribersIds_.size();
    }
    /**
     * <code>repeated int64 subscribersIds = 3;</code>
     * @param index The index of the element to return.
     * @return The subscribersIds at the given index.
     */
    public long getSubscribersIds(int index) {
      return subscribersIds_.getLong(index);
    }
    private int subscribersIdsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (postId_ != 0L) {
        output.writeInt64(1, postId_);
      }
      if (authorId_ != 0L) {
        output.writeInt64(2, authorId_);
      }
      if (getSubscribersIdsList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(subscribersIdsMemoizedSerializedSize);
      }
      for (int i = 0; i < subscribersIds_.size(); i++) {
        output.writeInt64NoTag(subscribersIds_.getLong(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (postId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, postId_);
      }
      if (authorId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, authorId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < subscribersIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(subscribersIds_.getLong(i));
        }
        size += dataSize;
        if (!getSubscribersIdsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        subscribersIdsMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PostPublishedEventProto.PostPublishedEvent)) {
        return super.equals(obj);
      }
      PostPublishedEventProto.PostPublishedEvent other = (PostPublishedEventProto.PostPublishedEvent) obj;

      if (getPostId()
          != other.getPostId()) return false;
      if (getAuthorId()
          != other.getAuthorId()) return false;
      if (!getSubscribersIdsList()
          .equals(other.getSubscribersIdsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POSTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPostId());
      hash = (37 * hash) + AUTHORID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAuthorId());
      if (getSubscribersIdsCount() > 0) {
        hash = (37 * hash) + SUBSCRIBERSIDS_FIELD_NUMBER;
        hash = (53 * hash) + getSubscribersIdsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PostPublishedEventProto.PostPublishedEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PostPublishedEventProto.PostPublishedEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PostPublishedEventProto.PostPublishedEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PostPublishedEventProto.PostPublishedEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PostPublishedEventProto.PostPublishedEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PostPublishedEventProto.PostPublishedEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PostPublishedEventProto.PostPublishedEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static PostPublishedEventProto.PostPublishedEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static PostPublishedEventProto.PostPublishedEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static PostPublishedEventProto.PostPublishedEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PostPublishedEventProto.PostPublishedEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static PostPublishedEventProto.PostPublishedEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PostPublishedEventProto.PostPublishedEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PostPublishedEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PostPublishedEvent)
        PostPublishedEventProto.PostPublishedEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PostPublishedEventProto.internal_static_PostPublishedEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PostPublishedEventProto.internal_static_PostPublishedEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PostPublishedEventProto.PostPublishedEvent.class, PostPublishedEventProto.PostPublishedEvent.Builder.class);
      }

      // Construct using PostPublishedEventProto.PostPublishedEvent.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        postId_ = 0L;
        authorId_ = 0L;
        subscribersIds_ = emptyLongList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PostPublishedEventProto.internal_static_PostPublishedEvent_descriptor;
      }

      @java.lang.Override
      public PostPublishedEventProto.PostPublishedEvent getDefaultInstanceForType() {
        return PostPublishedEventProto.PostPublishedEvent.getDefaultInstance();
      }

      @java.lang.Override
      public PostPublishedEventProto.PostPublishedEvent build() {
        PostPublishedEventProto.PostPublishedEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PostPublishedEventProto.PostPublishedEvent buildPartial() {
        PostPublishedEventProto.PostPublishedEvent result = new PostPublishedEventProto.PostPublishedEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(PostPublishedEventProto.PostPublishedEvent result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.postId_ = postId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.authorId_ = authorId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          subscribersIds_.makeImmutable();
          result.subscribersIds_ = subscribersIds_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PostPublishedEventProto.PostPublishedEvent) {
          return mergeFrom((PostPublishedEventProto.PostPublishedEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PostPublishedEventProto.PostPublishedEvent other) {
        if (other == PostPublishedEventProto.PostPublishedEvent.getDefaultInstance()) return this;
        if (other.getPostId() != 0L) {
          setPostId(other.getPostId());
        }
        if (other.getAuthorId() != 0L) {
          setAuthorId(other.getAuthorId());
        }
        if (!other.subscribersIds_.isEmpty()) {
          if (subscribersIds_.isEmpty()) {
            subscribersIds_ = other.subscribersIds_;
            subscribersIds_.makeImmutable();
            bitField0_ |= 0x00000004;
          } else {
            ensureSubscribersIdsIsMutable();
            subscribersIds_.addAll(other.subscribersIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                postId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                authorId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                long v = input.readInt64();
                ensureSubscribersIdsIsMutable();
                subscribersIds_.addLong(v);
                break;
              } // case 24
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureSubscribersIdsIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  subscribersIds_.addLong(input.readInt64());
                }
                input.popLimit(limit);
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long postId_ ;
      /**
       * <code>int64 postId = 1;</code>
       * @return The postId.
       */
      @java.lang.Override
      public long getPostId() {
        return postId_;
      }
      /**
       * <code>int64 postId = 1;</code>
       * @param value The postId to set.
       * @return This builder for chaining.
       */
      public Builder setPostId(long value) {

        postId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 postId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPostId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        postId_ = 0L;
        onChanged();
        return this;
      }

      private long authorId_ ;
      /**
       * <code>int64 authorId = 2;</code>
       * @return The authorId.
       */
      @java.lang.Override
      public long getAuthorId() {
        return authorId_;
      }
      /**
       * <code>int64 authorId = 2;</code>
       * @param value The authorId to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorId(long value) {

        authorId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 authorId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        authorId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.LongList subscribersIds_ = emptyLongList();
      private void ensureSubscribersIdsIsMutable() {
        if (!subscribersIds_.isModifiable()) {
          subscribersIds_ = makeMutableCopy(subscribersIds_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <code>repeated int64 subscribersIds = 3;</code>
       * @return A list containing the subscribersIds.
       */
      public java.util.List<java.lang.Long>
          getSubscribersIdsList() {
        subscribersIds_.makeImmutable();
        return subscribersIds_;
      }
      /**
       * <code>repeated int64 subscribersIds = 3;</code>
       * @return The count of subscribersIds.
       */
      public int getSubscribersIdsCount() {
        return subscribersIds_.size();
      }
      /**
       * <code>repeated int64 subscribersIds = 3;</code>
       * @param index The index of the element to return.
       * @return The subscribersIds at the given index.
       */
      public long getSubscribersIds(int index) {
        return subscribersIds_.getLong(index);
      }
      /**
       * <code>repeated int64 subscribersIds = 3;</code>
       * @param index The index to set the value at.
       * @param value The subscribersIds to set.
       * @return This builder for chaining.
       */
      public Builder setSubscribersIds(
          int index, long value) {

        ensureSubscribersIdsIsMutable();
        subscribersIds_.setLong(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 subscribersIds = 3;</code>
       * @param value The subscribersIds to add.
       * @return This builder for chaining.
       */
      public Builder addSubscribersIds(long value) {

        ensureSubscribersIdsIsMutable();
        subscribersIds_.addLong(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 subscribersIds = 3;</code>
       * @param values The subscribersIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllSubscribersIds(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureSubscribersIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, subscribersIds_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 subscribersIds = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSubscribersIds() {
        subscribersIds_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PostPublishedEvent)
    }

    // @@protoc_insertion_point(class_scope:PostPublishedEvent)
    private static final PostPublishedEventProto.PostPublishedEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PostPublishedEventProto.PostPublishedEvent();
    }

    public static PostPublishedEventProto.PostPublishedEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PostPublishedEvent>
        PARSER = new com.google.protobuf.AbstractParser<PostPublishedEvent>() {
      @java.lang.Override
      public PostPublishedEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PostPublishedEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PostPublishedEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PostPublishedEventProto.PostPublishedEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostPublishedEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PostPublishedEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032post_published_event.proto\"N\n\022PostPubl" +
      "ishedEvent\022\016\n\006postId\030\001 \001(\003\022\020\n\010authorId\030\002" +
      " \001(\003\022\026\n\016subscribersIds\030\003 \003(\003B\033\n\000B\027PostPu" +
      "blishedEventProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PostPublishedEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PostPublishedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PostPublishedEvent_descriptor,
        new java.lang.String[] { "PostId", "AuthorId", "SubscribersIds", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
